name: Generate & Copy Tokens
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_tokens:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
        with:
          node-version: '18'
      - run: npm install
      - run: node build.mjs
      - name: Commit and Push Changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "build tokens" || echo "No changes to commit"
          git push

  copy_tokens:
    runs-on: ubuntu-latest
    needs: build_tokens
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Clone Destination Repository
        run: |
          git clone https://x-access-token:${{ secrets.DESIGN_TOKEN }}@github.com/vemelin/tokens.git destination-repo
          cp -R build/. destination-repo/src/tokens/
          cd destination-repo
          git config user.name "vemelin"
          git config user.email "vemelin@gmail.com"
          git add .
          git commit -m "Copy SCSS tokens" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.DESIGN_TOKEN }}@github.com/vemelin/dst_tokens.git

#  copy_tokens:
#     runs-on: ubuntu-latest
#     needs: build_tokens
#     steps:
#       - uses: actions/checkout@v2
#         with:
#           fetch-depth: 0
#       - name: Clone Destination Repository
#         run: |
#           git clone https://x-access-token:${{ secrets.DESIGN_TOKEN }}@github.com/vemelin/dst_tokens.git destination-repo
#           cp -R build/. destination-repo/src/tokens/
#           cd destination-repo
#           git config user.name "vemelin"
#           git config user.email "vemelin@gmail.com"
#           git add .
#           git commit -m "Copy SCSS tokens" || echo "No changes to commit"
#           git push https://x-access-token:${{ secrets.DESIGN_TOKEN }}@github.com/vemelin/dst_tokens.git